export const SET_STEP_ONE_INPUT_VALUE = "SET_STEP_ONE_INPUT_VALUE";
export const SET_STEP_TWO_INPUT_VALUE = "SET_STEP_TWO_INPUT_VALUE";
export const UPDATE_PERIOD = "UPDATE_PERIOD";
export const UPDATE_ADDONS_PLANS = "UPDATE_ADDONS_PLANS";
export const CHANGE_PLANS = "CHANGE_PLANS";
export const NEXT_STEP = "NEXT_STEP";
export const PREV_STEP = "PREV_STEP";
