export const SET_STEP_ONE_INPUT_VALUE = "SET_STEP_ONE_INPUT_VALUE";
export const UPDATE_SELECTED_PLANS = "UPDATE_SELECTED_PLANS";
export const TOGGLE_PLANS_DURATION = "TOGGLE_PLANS_DURATION";
export const UPDATE_ADDONS_PLANS = "UPDATE_ADDONS_PLANS";
export const CHANGE_PLANS = "CHANGE_PLANS";
export const NEXT_STEP = "NEXT_STEP";
export const PREV_STEP = "PREV_STEP";
